//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpellWork.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Aura Type")]
        public string AuraTypeFilter {
            get {
                return ((string)(this["AuraTypeFilter"]));
            }
            set {
                this["AuraTypeFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public object SpellFamilyNameFilter {
            get {
                return ((object)(this["SpellFamilyNameFilter"]));
            }
            set {
                this["SpellFamilyNameFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public object SpellEffectFilter {
            get {
                return ((object)(this["SpellEffectFilter"]));
            }
            set {
                this["SpellEffectFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NO_TARGET")]
        public global::SpellWork.Enums.Targets TargerAFilter {
            get {
                return ((global::SpellWork.Enums.Targets)(this["TargerAFilter"]));
            }
            set {
                this["TargerAFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NO_TARGET")]
        public global::SpellWork.Enums.Targets TargetBFilter {
            get {
                return ((global::SpellWork.Enums.Targets)(this["TargetBFilter"]));
            }
            set {
                this["TargetBFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SpellNameFilter {
            get {
                return ((string)(this["SpellNameFilter"]));
            }
            set {
                this["SpellNameFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("350")]
        public int SpellListWidht {
            get {
                return ((int)(this["SpellListWidht"]));
            }
            set {
                this["SpellListWidht"] = value;
            }
        }
    }
}
